---
title: 'Case Study: Mobi Bikeshare in Vancouver'
author: "Andrew Luyt"
date: "07/07/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Mobi is a bikeshare in Vancouver, Canada. Launched in 2016, it is a cooperative
effort between the City of Vancouver and Shaw Go.

TBC...

## Goals of the Study
TBD, but some ideas:

- How has usage changed since 2016?
  - How has the network changed (where the stations are, # of bikes..)
  - Has usage gone up?
    - is it correlated to the expansion of the station network?
- Analyze usage patterns
  - when is bike rush hour? where?
    - visualize this on a map with scrubbable hour?
  - are there spikes on certain days?
    - a pattern, like on weekends?
    - holidays or other special dates?
  - how did COVID-19 affect MOBI usage?
    - highlight dates when lockdowns were initiated/removed in BC
  - visualize traffic hot spots
    - departure
    - arrival
      - is there a difference, a favored direction, etc?
  - how long are trips (time and distance)
    - does it change by hour? day of the week?
    - what were the longest trips?
- Analyze memberships
  - how do they change over time (2016 to now?)
  - have membership **renewal** rates gone up?
- What do the voltage columns mean?
  - voltage_return is **higher** than depart - why?
- stopovers
  - are people primarily commuting, or running errands with a stopover?
    - what's the distribution?
- bicycle attrition?
  - the `bike` column seems to record a unique bike ID - does it?
  - how long do bikes last? do they disappear from the dataset?
    - are all bikes used every day?
